# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiCalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 360)
        Form.setMinimumSize(QtCore.QSize(521, 360))
        Form.setMaximumSize(QtCore.QSize(521, 360))
        Form.setSizeIncrement(QtCore.QSize(521, 360))
        Form.setBaseSize(QtCore.QSize(521, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/calculator-icon/calculator-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QPushButton{\n"
"background: #fff;\n"
"width: 55px;\n"
"height: 50px;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"text-align: center;\n"
"border: none;\n"
"font-weight: 500;\n"
"text-transform: uppercase;\n"
"color: #111;\n"
"font-size: 18px;\n"
"border-radius: 40px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #8e8e93;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #fc3d39;\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLabel_2{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-size: 14px;\n"
"outline: none;\n"
"border: none;\n"
"background: #fff;\n"
"font-weight: 500;\n"
"color: #111;\n"
"font-size: 18px;\n"
"}\n"
"\n"
"QTextBrowser{\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"color: #000;\n"
"font-weight: 500;\n"
"text-transform: uppercase;\n"
"font-size: 14px;\n"
"}")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 431, 41))
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 241, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 4, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 2, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.pushButton_cn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cn.setStyleSheet("")
        self.pushButton_cn.setObjectName("pushButton_cn")
        self.gridLayout.addWidget(self.pushButton_cn, 4, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 4, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 1, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 0, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 0, 0, 1, 1)
        self.pushButton_BackSpace = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_BackSpace.setObjectName("pushButton_BackSpace")
        self.gridLayout.addWidget(self.pushButton_BackSpace, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 4, 1, 1, 1)
        self.btnResult = QtWidgets.QPushButton(Form)
        self.btnResult.setGeometry(QtCore.QRect(263, 253, 171, 31))
        self.btnResult.setStyleSheet("font-weight: 500;\n"
"text-transform: uppercase;\n"
"color: #000;\n"
"font-size: 18px;\n"
"\n"
"")
        self.btnResult.setAutoDefault(True)
        self.btnResult.setObjectName("btnResult")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(396, 340, 131, 20))
        self.label_2.setStyleSheet("color: #BCBCBC;")
        self.label_2.setObjectName("label_2")
        self.resText = QtWidgets.QLineEdit(Form)
        self.resText.setGeometry(QtCore.QRect(263, 300, 171, 41))
        self.resText.setObjectName("resText")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(263, 90, 171, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(288, 70, 131, 31))
        self.label_3.setStyleSheet("font-weight: 500;\n"
"text-transform: uppercase;\n"
"color: #000;\n"
"font-size: 16px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(263, 170, 171, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_3.addWidget(self.radioButton_8)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(340, 150, 16, 31))
        self.label_4.setStyleSheet("font-weight: 500;\n"
"text-transform: uppercase;\n"
"color: #000;\n"
"font-size: 16px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(450, 10, 59, 332))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout.addWidget(self.pushButton_12)
        self.pushButton_36 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout.addWidget(self.pushButton_36)
        self.pushButton_29 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout.addWidget(self.pushButton_29)
        self.pushButton_23 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout.addWidget(self.pushButton_23)
        self.pushButton_22 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout.addWidget(self.pushButton_22)
        self.pushButton_21 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout.addWidget(self.pushButton_21)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Калькулятор систем счисления"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Ведите число"))
        self.pushButton_14.setText(_translate("Form", "."))
        self.pushButton_10.setText(_translate("Form", "!"))
        self.pushButton_13.setText(_translate("Form", "+"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_cn.setText(_translate("Form", "CN"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_16.setText(_translate("Form", "="))
        self.pushButton_15.setText(_translate("Form", "-"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_20.setText(_translate("Form", "/"))
        self.pushButton_19.setText(_translate("Form", "%"))
        self.pushButton_BackSpace.setText(_translate("Form", "<--"))
        self.pushButton.setText(_translate("Form", "×"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.btnResult.setText(_translate("Form", "Перевести"))
        self.label_2.setText(_translate("Form", "by Khemraev Yusup"))
        self.resText.setPlaceholderText(_translate("Form", "Ответ"))
        self.radioButton.setText(_translate("Form", "2"))
        self.radioButton_2.setText(_translate("Form", "8"))
        self.radioButton_3.setText(_translate("Form", "10"))
        self.radioButton_4.setText(_translate("Form", "16"))
        self.label_3.setText(_translate("Form", "Перевести из"))
        self.radioButton_5.setText(_translate("Form", "2"))
        self.radioButton_6.setText(_translate("Form", "8"))
        self.radioButton_7.setText(_translate("Form", "10"))
        self.radioButton_8.setText(_translate("Form", "16"))
        self.label_4.setText(_translate("Form", "в"))
        self.pushButton_12.setText(_translate("Form", "A"))
        self.pushButton_36.setText(_translate("Form", "B"))
        self.pushButton_29.setText(_translate("Form", "C"))
        self.pushButton_23.setText(_translate("Form", "D"))
        self.pushButton_22.setText(_translate("Form", "E"))
        self.pushButton_21.setText(_translate("Form", "F"))
import rc_rc
